apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: talentlink-local
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: user-service
          image: ghcr.io/erfanalizada/talentlink_minikube-user-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: local
            - name: DATABASE_URL
              value: "postgresql://userservice:userservice123@userdb-postgres:5432/userdb"
            - name: UPLOAD_DIR
              value: "/app/uploads"
            - name: JAEGER_HOST
              value: "jaeger"
            - name: JAEGER_PORT
              value: "6831"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "talentlink"
            - name: RABBITMQ_PASS
              value: "talentlink123"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/users/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/users/health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: uploads
          emptyDir: {}
