apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-service
  namespace: talentlink-local
  labels:
    app: job-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-service
  template:
    metadata:
      labels:
        app: job-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: job-service
          image: ghcr.io/erfanalizada/talentlink_minikube-job-service:latest   # 👈 GHCR image
          imagePullPolicy: Always                          # 👈 Always pull newest image
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: local
            - name: DATABASE_URL
              value: "postgresql://jobservice:jobservice123@jobdb-postgres:5432/jobdb"
            - name: UPLOAD_DIR
              value: "/app/uploads"
            - name: JAEGER_HOST
              value: "jaeger"
            - name: JAEGER_PORT
              value: "6831"
          volumeMounts:
            - name: uploads
              mountPath: /app/uploads
          readinessProbe:
            httpGet:
              path: /api/jobs/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/jobs/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
      volumes:
        - name: uploads
          emptyDir: {}
