apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: talentlink-local
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: matching-service
          image: ghcr.io/erfanalizada/talentlink_minikube-matching-service:latest   # 👈 GHCR image
          imagePullPolicy: Always                               # 👈 Always pull new
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: local
          readinessProbe:
            httpGet:
              path: /api/matching/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/matching/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
