apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: talentlink-local
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service
          image: ghcr.io/erfanalizada/talentlink_minikube-notification-service:latest   # 👈 GHCR image
          imagePullPolicy: Always                                   # 👈 Always pull latest
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: local
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "talentlink"
            - name: RABBITMQ_PASS
              value: "talentlink123"
            - name: JOB_SERVICE_URL
              value: "http://job-service:5000"
            - name: SMTP_HOST
              value: "smtp.gmail.com"
            - name: SMTP_PORT
              value: "587"
            - name: SMTP_USER
              value: ""
            - name: SMTP_PASS
              value: ""
            - name: SENDER_EMAIL
              value: "noreply@talentlink.com"
            - name: SENDER_NAME
              value: "Talentlink"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /api/notifications/health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/notifications/health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
